Major refactor ongoing

diff --git a/draft/Makefile b/draft/Makefile
--- a/draft/Makefile
+++ b/draft/Makefile
@@ -1,79 +1,181 @@
-# Makefile for compiling RMarkdown documents
-# Document name (no file extension)
-PAPER = kerswell-kohn-backarc
-SUPP = kerswell-kohn-backarc-supporting
-DIFF = g3_submission/kerswell-kohn-backarc
-FIGSDIR = assets/figs
-# pdflatex command
-LTXFLAGS = "--shell-escape -interaction=nonstopmode -file-line-error -synctex=1 %O %S"
-# Strings to search for in log file for rerunning pdflatex until all
-# cross references and other issues are resolved
-RERUN := "(Rerun to get (cross-references|the bars|point totals) right|Table widths have changed. Rerun LaTeX.|Linenumber reference failed|has been referenced but does not)"
-# Same for bibliography
-RERUNBIB := "No file.*\.bbl|Citation.*undefined"
+# Top-level dirs
+PROJECT_ROOT := $(realpath $(dir $(lastword $(MAKEFILE_LIST)))/..)
+R := $(PROJECT_ROOT)/R
+DRAFT := $(PROJECT_ROOT)/draft
 
-# Top level
-all: paper supp
+# Manuscript
+TEMPLATE := $(DRAFT)/eisvogel.tex
+YAML := $(DRAFT)/eisvogel.yaml
+SI_YAML := $(DRAFT)/eisvogel-si.yaml
+# TEMPLATE := $(DRAFT)/agu.tex
+# YAML := $(DRAFT)/agu.yaml
+# SI_YAML := $(DRAFT)/agu-si.yaml
+CSL := $(DRAFT)/agu.csl
+BIB := $(DRAFT)/main.bib
+DOC := $(DRAFT)/manuscript
+SI := $(DRAFT)/supplementary-information
+PREV_DOC := $(DRAFT)/bak/manuscript-28-oct-2025
+DIFF_DOC := $(DRAFT)/diff
 
-# Doc requires the pdf file
-paper: $(PAPER).pdf
-	@open $<
+# Cleanup targets
+CLEAN := $(DOC).{tex,pdf,aux,bbl,blg,log,toc} $(DIFF_DOC).{tex,pdf,aux,bbl,blg,log,toc} $(SI).{tex,pdf,aux,bbl,blg,log,toc}
+# DEEP_CLEAN := $(PROJECT_ROOT)/figs
+DEEP_CLEAN :=
 
-supp: $(SUPP).pdf
-	@open $<
+# Targets
+.PHONY: all diff manuscript supp update-date clean deep-clean help
 
-diff: diff.tex
-	
-upload: $(PAPER).Rmd $(PAPER).pdf
-	@printf "\nUploading %s to google docs trackdown/%s\n" "$(PAPER)"
-	@Rscript assets/r/upload-google.R $(PAPER).Rmd $(PAPER).pdf $(FIGSDIR) upload
+all: manuscript
 
-update: $(PAPER).Rmd $(PAPER).pdf
-	@printf "\nUploading %s to google docs trackdown/%s\n" "$(PAPER)"
-	@Rscript assets/r/upload-google.R $(PAPER).Rmd $(PAPER).pdf $(FIGSDIR) update
+diff: $(DIFF_DOC).pdf
 
-download: $(PAPER).Rmd
-	@printf "\nDownloading %s from google docs trackdown/%s\n" "$(PAPER)"
-	@Rscript assets/r/upload-google.R $(PAPER).Rmd $(PAPER).pdf $(FIGSDIR) download
+manuscript: $(DOC).tex $(DOC).pdf
 
-# Main level
-# pdf file requires compiling the tex file
-# using pdflatex and bibtex
-$(PAPER).pdf: $(PAPER).tex
-	@printf "\nPDFLaTeX for %s ..." "$(PAPER)"
-	@pdflatex $(LTXFLAGS) $< > /dev/null 2>&1
-	@while(egrep -q $(RERUNBIB) $(PAPER).log > /dev/null 2>&1 && bibtex $(PAPER) > /dev/null 2>&1 && pdflatex $(LTXFLAGS) $< > /dev/null 2>&1) do \
-		echo "\nRerunning BibTeX ..." ; done
-	@while(egrep $(RERUN) $(PAPER).log > /dev/null 2>&1 && pdflatex $(LTXFLAGS) $< > /dev/null 2>&1) do \
-		echo "\nRerunning PDFLaTeX ..." ; done
-$(SUPP).pdf: $(SUPP).tex
-	@printf "\nPDFLaTeX for %s ..." "$(SUPP)"
-	@pdflatex $(LTXFLAGS) $< > /dev/null 2>&1
-	@while(egrep -q $(RERUNBIB) $(SUPP).log > /dev/null 2>&1 && bibtex $(SUPP) > /dev/null 2>&1 && pdflatex $(LTXFLAGS) $< > /dev/null 2>&1) do \
-		echo "\nRerunning BibTeX ..." ; done
-	@while(egrep $(RERUN) $(SUPP).log > /dev/null 2>&1 && pdflatex $(LTXFLAGS) $< > /dev/null 2>&1) do \
-		echo "\nRerunning PDFLaTeX ..." ; done
+supp: $(SI).tex $(SI).pdf
 
-# Lowest level
-# tex document requires knitting by calling
-# rmarkdown::render in R
-$(PAPER).tex: $(PAPER).Rmd
-	@printf "\nRmarkdown Render for %s ..." "$(PAPER)"
-	@R -q -e 'rmarkdown::render("$(PAPER).Rmd", quiet = T, clean = F)' > /dev/null 2>&1
-	@rm -f $(PAPER).pdf
-$(SUPP).tex: $(SUPP).Rmd
-	@printf "\nRmarkdown Render for %s ..." "$(SUPP)"
-	@R -q -e 'rmarkdown::render("$(SUPP).Rmd", quiet = T, clean = F)' > /dev/null 2>&1
-	@rm -f $(SUPP).pdf
-diff.tex: $(PAPER).tex $(DIFF).tex
-	@printf "\nlatexdiff for %s vs. %s ..." "$(DIFF).tex" "$(PAPER).tex"
-	@latexdiff --type=CFONT --disable-citation-markup --graphics-markup=none --allow-spaces $(DIFF).tex $(PAPER).tex > diff.tex
+$(DIFF_DOC).pdf: $(PREV_DOC).tex $(DOC).tex
+	@echo "    --------------------------------------------------"
+	@echo "    Rendering manuscript diff"
+	@echo "    --------------------------------------------------"
+	@echo " -> Comparing $(shell basename $(PREV_DOC).tex) with $(shell basename $(DOC).tex)"
+	@latexdiff \
+	  --flatten \
+	  --math-markup=0 \
+	  --type=CFONT \
+	  --exclude-textcmd=caption \
+	  --add-to-config PICTUREENV=longtable \
+	  --graphics-markup=none \
+	  $(PREV_DOC).tex $(DOC).tex > $(DIFF_DOC).tex 2> /dev/null
+	@echo " -> Rendering $(shell basename $(DIFF_DOC).pdf) from $(shell basename $(DIFF_DOC).tex)"
+	@pdflatex -interaction=nonstopmode -shell-escape -output-directory $(DRAFT) $(DIFF_DOC).tex > /dev/null 2>&1 || true
+	@pdflatex -interaction=nonstopmode -shell-escape -output-directory $(DRAFT) $(DIFF_DOC).tex > /dev/null 2>&1 || true
 
-# purge auxillary files
-purge:
-	@rm -f *.{html,acr,alg,gz,glg,gls,ilg,nls,acn,glo,ist,lof,lot,nlo,aux,dvi,log,bbl,blg,brf,fls,toc,thm,out,fdb_latexmk,tex,md,pdf}
+$(DOC).pdf: update-date
+	@echo " -> Rendering $(shell basename $(DOC).pdf) from $(shell basename $(DOC).tex)"
+	@if [ "$(shell basename $(TEMPLATE))" = "eisvogel.tex" ]; then \
+	  pandoc "$(DOC).md" -o "$(DOC).pdf" \
+	    --from markdown \
+	    --template "$(TEMPLATE)" \
+	    --metadata-file=$(YAML) \
+	    --bibliography=$(BIB) \
+	    --csl=$(CSL) \
+	    --filter=pandoc-crossref \
+	    --citeproc \
+	    --pdf-engine=pdflatex \
+	    --pdf-engine-opt="-shell-escape" \
+	    --pdf-engine-opt="-interaction=nonstopmode"; \
+	else \
+	  pdflatex -interaction=nonstopmode -shell-escape -output-directory $(DRAFT) $(DOC).tex > /dev/null 2>&1 || true; \
+	  cd $(DRAFT) && bibtex $(notdir $(DOC)) > /dev/null 2>&1; \
+	  pdflatex -interaction=nonstopmode -shell-escape -output-directory $(DRAFT) $(DOC).tex > /dev/null 2>&1 || true; \
+	  pdflatex -interaction=nonstopmode -shell-escape -output-directory $(DRAFT) $(DOC).tex > /dev/null 2>&1 || true; \
+	fi
 
-# clean directory (excluding .Rmd file)
-clean: purge
+$(SI).pdf: update-date
+	@echo " -> Rendering $(shell basename $(SI).pdf) from $(shell basename $(SI).tex)"
+	@if [ "$(shell basename $(TEMPLATE))" = "eisvogel.tex" ]; then \
+	  pandoc "$(SI).md" -o "$(SI).pdf" \
+	    --from markdown \
+	    --template "$(TEMPLATE)" \
+	    --metadata-file=$(SI_YAML) \
+	    --bibliography=$(BIB) \
+	    --csl=$(CSL) \
+	    --filter=pandoc-crossref \
+	    --citeproc \
+	    --pdf-engine=pdflatex \
+	    --pdf-engine-opt="-shell-escape" \
+	    --pdf-engine-opt="-interaction=nonstopmode"; \
+	else \
+	  pdflatex -interaction=nonstopmode -shell-escape -output-directory $(DRAFT) $(SI).tex > /dev/null 2>&1 || true; \
+	  cd $(DRAFT) && bibtex $(notdir $(SI)) > /dev/null 2>&1; \
+	  pdflatex -interaction=nonstopmode -shell-escape -output-directory $(DRAFT) $(SI).tex > /dev/null 2>&1 || true; \
+	  pdflatex -interaction=nonstopmode -shell-escape -output-directory $(DRAFT) $(SI).tex > /dev/null 2>&1 || true; \
+	fi
 
-.PHONY: all paper supp diff upload update download purge clean
+$(DOC).tex: update-date
+	@echo "    --------------------------------------------------"
+	@echo "    Rendering manuscript"
+	@echo "    --------------------------------------------------"
+	@echo " -> Rendering $(shell basename $(DOC).md) with $(shell basename $(TEMPLATE)) template"
+	@if [ "$(shell basename $(TEMPLATE))" = "eisvogel.tex" ]; then \
+	  pandoc "$(DOC).md" -s -o "$(DOC).tex" \
+	    --from markdown \
+	    --template "$(TEMPLATE)" \
+	    --metadata-file=$(YAML) \
+	    --bibliography=$(BIB) \
+	    --csl=$(CSL) \
+	    --filter=pandoc-crossref \
+	    --citeproc; \
+	else \
+	  pandoc "$(DOC).md" -o "$(DOC).tex" \
+	    --from markdown \
+	    --template "$(TEMPLATE)" \
+	    --metadata-file=$(YAML) \
+	    --bibliography=$(BIB) \
+	    --filter=pandoc-crossref \
+	    --natbib; \
+	fi
+
+$(SI).tex: update-date
+	@echo "    --------------------------------------------------"
+	@echo "    Rendering manuscript"
+	@echo "    --------------------------------------------------"
+	@echo " -> Rendering $(shell basename $(SI).md) with $(shell basename $(TEMPLATE)) template"
+	@if [ "$(shell basename $(TEMPLATE))" = "eisvogel.tex" ]; then \
+	  pandoc "$(SI).md" -s -o "$(SI).tex" \
+	    --from markdown \
+	    --template "$(TEMPLATE)" \
+	    --metadata-file=$(SI_YAML) \
+	    --bibliography=$(BIB) \
+	    --csl=$(CSL) \
+	    --filter=pandoc-crossref \
+	    --citeproc; \
+	else \
+	  pandoc "$(SI).md" -o "$(SI).tex" \
+	    --from markdown \
+	    --template agu-si.tex \
+	    --metadata-file=$(SI_YAML) \
+	    --bibliography=$(BIB) \
+	    --csl=$(CSL) \
+	    --filter=pandoc-crossref \
+	    --natbib; \
+	fi
+
+update-date:
+	@sed -i '' -E "s/^date: \".*\"/date: \"$(shell date '+%d %B %Y')\"/" $(DOC).md
+
+clean:
+	@for item in $(CLEAN); do \
+		safe_rm() { \
+			if [ -e "$$1" ]; then \
+				ABS_PATH=$$(realpath "$$1"); \
+				if [[ "$$ABS_PATH" == $(PROJECT_ROOT)* ]]; then \
+					echo " -> Safely removing: $$ABS_PATH"; \
+					rm -rf "$$ABS_PATH"; \
+				fi; \
+			fi; \
+		}; \
+		safe_rm "$$item"; \
+	done
+
+deep-clean:
+	@for item in $(DEEP_CLEAN); do \
+		safe_rm() { \
+			if [ -e "$$1" ]; then \
+				ABS_PATH=$$(realpath "$$1"); \
+				if [[ "$$ABS_PATH" == $(PROJECT_ROOT)* ]]; then \
+					echo " -> Safely removing: $$ABS_PATH"; \
+					rm -rf "$$ABS_PATH"; \
+				fi; \
+			fi; \
+		}; \
+		safe_rm "$$item"; \
+	done
+
+help:
+	@echo "    --------------------------------------------------"
+	@echo "    Available targets:"
+	@echo "    --------------------------------------------------"
+	@echo "    clean       Cleanup unnecessary files and directories (safe)"
+	@echo "    deep-clean  Deep clean figures and results (use with caution!)"
+	@echo "    help        Show this help message"
